apiVersion: windows.k8s.io/v1alpha1
kind: Node
metadata:
  name: winworker
spec:
  credentials:
    hostname: "192.168.10.3:22"
    username: "Administrator"
    privateKey: ".\\experiments\\swdt\\samples\\mloskot\\ssh.id_rsa"
  setup:
    enableRDP: true
    chocoPackages:
    - vim
    - grep
