apiVersion: windows.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: config-cluster
spec:
  version: v1.29.0

  controlPlane:
    minikube: true

  workload:
    virtualization:
      kvmQemuURI: "qemu:///system"
      diskPath: "path"
      ssh:
        username: "Administrator"
        hostname: "192.168.122.220:22"  # autofilling if not passed
        key: "/home/<user>/.ssh/id_rsa"

    auxiliary:
      enableRDP: true
      chocoPackages:
      - vim
      - grep

    provisioners:
    - name: containerd
      version: 1.7.11
      sourceURL: "/home/<user>/go/src/github.com/containerd/containerd/bin/containerd"
      destination: "C:\\Program Files\\containerd\\containerd.exe"
    - name: kubelet
      version: 1.29.0
      sourceURL: "/home/<user>/go/src/k8s.io/kubernetes/_output/local/bin/windows/amd64/kubelet.exe"
      destination: "C:\\k\\kubelet.exe"
