apiVersion: windows.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: config-cluster
spec:
  controlPlane:
    kubernetesVersion: v1.28.3
    minikube: true
  workload:
    containerdVersion: 1.7.14
    kubernetesVersion: v1.29.0
    virtualization:
      kvmQemuURI: "qemu:///system"
      diskPath: "/home/aknabben/go/src/github.com/knabben/swdt/packer/output/win2k22"
      ssh:
        username: "Administrator"
        privateKey: "/home/aknabben/.ssh/id_rsa"
    auxiliary:
      enableRDP: false
      chocoPackages:
    provisioners:
    - name: containerd
      version: 1.7.11
      sourceURL: "/home/<user>/go/src/github.com/containerd/containerd/bin/containerd"
      destination: "C:\\Program Files\\containerd\\containerd.exe"
    - name: kubelet
      version: 1.29.0
      sourceURL: "/home/<user>/go/src/k8s.io/kubernetes/_output/local/bin/windows/amd64/kubelet.exe"
      destination: "C:\\k\\kubelet.exe"
