kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: {{ .KUBERNETES_SERVICE_HOST }}
  KUBERNETES_SERVICE_PORT: {{ .KUBERNETES_SERVICE_PORT }}