apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspdotnet
  labels:
    app: aspdotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspdotnet
  template:
    metadata:
      labels:
        app: aspdotnet
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: aspdotnet
        image:  mcr.microsoft.com/dotnet/samples:aspnetapp-8.0-nanoserver-ltsc2022
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aspdotnet
  labels:
    app: aspdotnet
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: aspdotnet
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: netshoot
  name: netshoot
spec:
  containers:
  - command:
    - sleep
    - "360000"
    image: nicolaka/netshoot:latest
    name: netshoot
    resources: {}
  nodeSelector:
    kubernetes.io/os: linux
